version: '3'
services:
  sample5:
    build:
      context: ./sample_app5/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env/env_file
    ports:
      - "8080:8080"	
    depends_on:
      - db
    networks: 
      - test-network
  db:
    image: postgres:11.5
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dev"
    volumes:
       - ./volumes/postgres:/var/lib/postgresql/data
    networks: 
      - test-network
networks: 
  test-network:
    external: true  