version: '3'
services:
  sample5:
    build:
      context: ./sample_app5/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env/env_file
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - test-network
  db:
    image: postgres:11.5
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./forDocker/db/initdb:/docker-entrypoint-initdb.d
    networks: 
      - test-network
networks: 
  test-network:
    external: true  
volumes:
  dbvol: