spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/test_db?user=postgres&password=postgres
    url: jdbc:postgresql://db:5432/test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
mybatis:
  configuration: 
    map-underscore-to-camel-case: true
